# Conexion a base de datos mysql
server: 
  port: 8080
spring:
  application:
    name: app-joinfaces-sb3-jsf
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appjoinfacesdb?useTimezone=true&serverTimezone=America/El_Salvador&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root2024$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
joinfaces:
  faces.project-stage: development
  faces-servlet.name: FacesServlet
  faces-servlet:
    url-mappings: '*.xhtml,'
  faces:
    project-stage: development
    state-saving-method: server
    validate-empty-fields: 'true'
  primefaces:
    theme: vela
