# Conexion a base de datos mysql
spring:
  profiles:
    active: dev
    default: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appjoinfacesdb?useTimezone=true&serverTimezone=America/El_Salvador&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root2024$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true